modLoader="javafml"
loaderVersion="[1,)"
license="All Rights Reserved"

[[mods]]
modId="cs2knifeanim"
version="1.0.0"
displayName="CS2 Knife Animation"
description="Replace sword swing animation with CS2 M9 bayonet draw animation"

[[dependencies.cs2knifeanim]]
modId="neoforge"
type="required"
versionRange="[26.3.0.8-beta,)"
ordering="NONE"
side="BOTH"

[[dependencies.cs2knifeanim]]
modId="minecraft"
type="required"
versionRange="[26.3,)"
ordering="NONE"
side="BOTH"
[[mixins]]
config="cs2knifeanim.mixins.json"
